apiVersion: batch/v1
kind: Job
metadata:
  name: v0.15.0-upgrade
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: "v0.15.2"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: eventing-controller
      restartPolicy: Never
      containers:
      - name: upgrade-brokers
        image: gcr.io/knative-releases/knative.dev/eventing/cmd/upgrade/v0.15.0@sha256:9447ebb06cd9d516e03ca3f42e8c374ab50226ff3affbd283490d56ee8189521

---
